project:
  type: website

website:
  title: "Gitactions website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tab-one/tab-one-index.qmd
        text: Tab-one
    logo: images/logo_tepak.png

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



